# Generated by Django 4.0.6 on 2024-08-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF ou CNPJ do produtor', max_length=18, unique=True)),
                ('usa_cpf', models.BooleanField(default=True, help_text='Se o produtor usa CPF (True) ou CNPJ (False)')),
                ('nome', models.CharField(help_text='Nome do produtor', max_length=100)),
                ('nome_fazenda', models.CharField(help_text='Nome da fazenda', max_length=100)),
                ('cidade', models.CharField(help_text='Cidade onde a fazenda está localizada', max_length=100)),
                ('estado', models.CharField(help_text='Estado onde a fazenda está localizada', max_length=2)),
                ('area_total_hectares', models.DecimalField(decimal_places=2, help_text='Área total da fazenda em hectares', max_digits=10)),
                ('area_agricultavel_hectares', models.DecimalField(decimal_places=2, help_text='Área agricultável em hectares', max_digits=10)),
                ('area_vegetacao_hectares', models.DecimalField(decimal_places=2, help_text='Área de vegetação em hectares', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Soja', 'Soja'), ('Milho', 'Milho'), ('Algodão', 'Algodão'), ('Café', 'Café'), ('Cana de Açúcar', 'Cana de Açúcar')], help_text='Nome da cultura', max_length=50, unique=True)),
                ('produtor_rural', models.ForeignKey(help_text='Produtor rural que cultiva essa cultura', on_delete=django.db.models.deletion.CASCADE, to='produtor_rural.produtorrural')),
            ],
        ),
    ]
