# Generated by Django 4.0.6 on 2024-08-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='nome',
            field=models.CharField(choices=[('Soja', 'Soja'), ('Milho', 'Milho'), ('Algodão', 'Algodão'), ('Café', 'Café'), ('Cana de Açúcar', 'Cana de Açúcar')], help_text='Nome da cultura', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cultura',
            constraint=models.UniqueConstraint(fields=('nome', 'produtor_rural'), name='unique_cultura_per_produtor'),
        ),
    ]
